import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "../styles/globals.css";
import Header from "../components/Header/Header";
import { FavoritesProvider } from '@/context/FavoritesContext';

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: '400',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={barlow.variable}>
      <body>
        <Header />
        <main role="main" className="container mx-auto px-4">
          <FavoritesProvider>
            {children}
          </FavoritesProvider>
        </main>
      </body>
    </html>
  );
}
